name: test
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: htmlproofer cache
        uses: actions/cache@v4
        with:
          path: public/linter-cache.json
          key: {{ runner.os }}-htmlproofer
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: |
              go.sum
              .bingo/**.sum
      - name: Build and lint the site
        run: make lint
